fixtures:
  symlinks:
    vault: "#{source_dir}"
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    archive: "puppet/archive"
    systemd: "camptocamp/systemd"
    file_capability: "stm/file_capability"
