---
.gitignore:
  paths:
    - .rerun.json
    - .librarian
    - .kitchen
    - .tmp
    - .bundle
    - bolt.log
    - Puppetfile.lock
    - modules
.gitlab-ci.yml:
  # we don't use GitLab
  unmanaged: true
appveyor.yml:
  # we don't use Appveyor
  unmanaged: true
Gemfile:
  required:
    ':development':
      - gem: 'puppet-blacksmith'
        version: '>= 5.0.0'
      - gem: 'puppet-lint-absolute_template_path'
        version: '>= 1.0.1'
      - gem: 'puppet-lint-alias-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-classes_and_types_beginning_with_digits-check'
        version: '>= 0.1.2'
      - gem: 'puppet-lint-concatenated_template_files-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-file_ensure-check'
        version: '>= 0.3.1'
      - gem: 'puppet-lint-file_source_rights-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-leading_zero-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-resource_reference_syntax'
        version: '>= 1.0.10'
      - gem: 'puppet-lint-trailing_comma-check'
        version: '>= 0.3.2'
      - gem: 'puppet-lint-unquoted_string-check'
        version: '>= 0.3.0'
      - gem: 'puppet-lint-version_comparison-check'
        version: '>= 0.2.1'
      - gem: 'r10k'
        version: '>= 3.0.0'
      # cri is needed by r10k, but due to a bug in the cri gem v2.15.7 it breaks r10k
      # see: https://github.com/puppetlabs/r10k/issues/930
      - gem: 'cri'
        version: '2.15.6'
      - gem: 'rspec-json_expectations'
        version: '>= 2.2.0'
      - gem: 'yaml-lint'
        version: '>= 0.0.10'
# Rakefile:
#   extras:
#     - "# exclude plans because puppet-syntax doesn't support them yet: https://github.com/voxpupuli/puppet-syntax/issues/95"
#     - 'PuppetSyntax.exclude_paths = ["plans/**/*", "vendor/**/*"]'
spec/spec_helper.rb:
  mock_with: ':rspec'
.travis.yml:
  # we've converted over to GitHub actions
  unmanaged: true
# .travis.yml:
#   deploy_to_forge:
#     enabled: true
#   user: encore
#   secure: "ntIpKlxSk9b4T++GJP1MiF2TuZwpeENibVAYRhfw1BsPDMJ0iM1QYjt01LXu2f6AUz3mz3/uIvPWUJgVyoQTOh32jJVZ1pHjr0rj6yC/De+smZM7LyIYFNqYPwzet+vIfgd2pFLmSDIAQwUERx61OTg+zuFO/29fOscZOtKL3gUBG1OTk0bGsCmhITjcoJeFmWksNQgLahooWfYvzP6zaVPdHEw1geES5sHYeXVS8HkqfNooyu5H2rqVpXlkNKKKzZCT0VAUrkwgveTlR8rY4rCMl62e9/lUvon69nEqjvWp/msmNvbhTjdqgWQ6xcL9LBGR9achIdQh19kybBfvMqzewweRS4rYoJwasjTSGebXH4aKsd1QSMZ3vcb2CNnt+z9sotLYRzPISVmGMvntuaa1JTQFY+ccQ7a5WmmL9XRe0EgJWmWUUSRQAJoGRi12UCtSRMhZTxTfylHPFIvUznhmfu3urXAwLpq4/yXI2/IhBQLVN7GzCy7kzPr+amWTgFvEf8b8ggSApAyMp6G24hwCMZiUvsK0klIkN/wsylKyvIed2kdPV6vTn7Uh5TYPOBAOgZBI0Xa0mBUol3MTSkP4yM9hMAK3buGJrxpvyEillO/8njkiCSxH7EYW5WGNR9x0BauxVkAmkegm1oqdfRInVeY4/0PjzcFKJoCWsSk="

